import LinksView from "@/components/admin-links/links-view";
import prisma from "@/lib/prisma";
import {
  AppearanceProps,
  getLinks,
  incrementLinkhubVisit,
  LinkSchema,
  LinksFormProps,
} from "@/modules/admin";
import { Box } from "@chakra-ui/react";
import { GetStaticPaths, GetStaticProps, NextPage } from "next";
import Head from "next/head";
import { useRouter } from "next/router";
import { ParsedUrlQuery } from "querystring";
import { useEffect } from "react";
import { z } from "zod";

interface Params extends ParsedUrlQuery {
  username: string;
}

export const getStaticPaths: GetStaticPaths<Params> = async () => {
  const users = await prisma.user.findMany();
  const usernames = users.map((user) => ({
    params: {
      username: user.username,
    },
  }));
  return {
    paths: usernames,
    fallback: true,
  };
};

export const getStaticProps: GetStaticProps<LinksFormProps, Params> = async (
  context
) => {
  const { username } = context.params!;
  const linksInfo = await prisma.user.findUnique({
    where: { username },
    select: {
      appearanceSettings: {
        select: {
          colorMode: true,
          linkhubBackgroundColor1: true,
          linkhubBackgroundColor2: true,
          linkhubTextColor: true,
        },
      },
      links: true,
    },
  });

  if (!linksInfo) return { notFound: true };

  let links = z.array(LinkSchema).parse(linksInfo?.links);
  links = links.filter((item) => item.enabled);
  links.forEach((item) => {
    // @ts-ignore
    delete item.viewCount;
  });
  return {
    props: {
      links,
      appearance: (linksInfo?.appearanceSettings as AppearanceProps),
    },
  };
};

const Linkhub: NextPage<LinksFormProps> = (props) => {
  const { query } = useRouter();
  const username: string = query.username as string;

  useEffect(() => {
    incrementLinkhubVisit(username);
  }, [username]);

  return (
    <>
      <Head>
        <title>{`Linkhub | ${username}`}</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Box minW="100vw" h="1" minH="100vh">
        <LinksView username={username} links={props} />
      </Box>
    </>
  );
};

export default Linkhub;
