import LinksView from "@/components/admin-links/links-view";
import prisma from "@/lib/prisma";
import { getLinks, incrementLinkhubVisit, LinksFormProps } from "@/modules/admin";
import { Box } from "@chakra-ui/react";
import { GetStaticPaths, GetStaticProps, NextPage } from "next";
import Head from "next/head";
import { useRouter } from "next/router";
import { ParsedUrlQuery } from "querystring";
import { useEffect } from "react";

interface Params extends ParsedUrlQuery { username: string; };

export const getStaticPaths: GetStaticPaths<Params> = async () => {
  const users = await prisma.user.findMany();
  const usernames = users.map((user) => ({
    params: {
      username: user.username,
    },
  }));
  return {
    paths: usernames,
    fallback: false,
  };
};

export const getStaticProps: GetStaticProps<LinksFormProps, Params> = async (context) => {
  const { username } = context.params!;
  const links = await getLinks(username);
  return { props: links };
}

const Linkhub: NextPage<LinksFormProps> = (props) => {
  const { query } = useRouter();
  const username: string = query.username as string;

  useEffect(() => {
    incrementLinkhubVisit(username);
  }, []);

  return (
    <>
      <Head>
        <title>{`Linkhub | ${username}`}</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Box minW="100vw" h="1" minH="100vh">
        <LinksView username={username} links={props} />
      </Box>
    </>
  );
}

export default Linkhub;
