import React, { useState } from "react";
import Head from "next/head";
import NextLink from "next/link";
import {
  Box,
  Flex,
  Heading,
  HStack,
  VStack,
  Link,
  Show,
  Hide,
  IconButton,
  useDisclosure,
  Drawer,
  DrawerOverlay,
  DrawerContent,
  DrawerCloseButton,
  DrawerBody,
  LinkBox,
  LinkOverlay,
  Divider,
  Text,
  InputGroup,
  InputLeftAddon,
  Input,
  Image,
  Grid,
} from "@chakra-ui/react";
import Button from "@/components/button";
import { HiOutlineMenu } from "react-icons/hi";
import Features from "@/components/landing-page/features";

export default function LandingPage() {
  return (
    <>
      <Head>
        <title>Linkhub: link in bio tool</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      <Box
        backgroundColor="gray.800"
        minW="100vw"
        minH="100vh"
        py="8"
        overflowX="clip"
      >
        <Box w={["90%", "80%"]} mx="auto">
          <Hero />
        </Box>
      </Box>
      <Features />
    </>
  );
}

function Navbar() {
  const { isOpen, onOpen, onClose } = useDisclosure();
  const navLinks = [
    { text: "Features", href: "#features" },
    { text: "Got Questions?", href: "#questions" },
  ];
  return (
    <>
      <Flex
        justifyContent="space-between"
        backgroundColor="whiteAlpha.900"
        rounded="2xl"
        px={{ base: "5", lg: "20" }}
        py="3"
        wrap="wrap"
        position="fixed"
        top="10"
        left="0"
        right="0"
        mx="auto"
        w={["90%", "80%"]}
        zIndex="3"
      >
        <HStack spacing="8" align="center">
          <Heading size={{ base: "md", lg: "lg" }}>Linkhub</Heading>
          <Show above="md">
            {navLinks.map((link, idx) => (
              <Link
                key={idx}
                as={NextLink}
                href={link.href}
                fontSize={{ base: "sm", lg: "md" }}
                color="gray.600"
              >
                {link.text}
              </Link>
            ))}
          </Show>
        </HStack>
        <HStack>
          <Button variant="outline" size={{ base: "sm", lg: "md" }}>
            Log In
          </Button>
          <Button variant="solid" size={{ base: "sm", lg: "md" }}>
            Sign Up
          </Button>
          <Hide above="md">
            <IconButton
              aria-label="Nav Links"
              icon={<HiOutlineMenu />}
              onClick={onOpen}
            />
          </Hide>
        </HStack>
      </Flex>
      <Drawer placement="right" isOpen={isOpen} onClose={onClose} size="full">
        <DrawerOverlay />
        <DrawerContent>
          <DrawerCloseButton />
          <DrawerBody>
            <VStack spacing="5" pt="14">
              {navLinks.map((link, idx) => (
                <React.Fragment key={idx}>
                  <LinkBox
                    as="div"
                    w="full"
                    p="3"
                    rounded="md"
                    _hover={{ backgroundColor: "gray.100" }}
                  >
                    <LinkOverlay as={NextLink} href={link.href}>
                      <Text as="b" fontSize="2xl">
                        {link.text}
                      </Text>
                    </LinkOverlay>
                  </LinkBox>
                  {idx !== navLinks.length - 1 && <Divider />}
                </React.Fragment>
              ))}
            </VStack>
          </DrawerBody>
        </DrawerContent>
      </Drawer>
    </>
  );
}

function Hero() {
  const [name, setName] = useState("");

  return (
    <Grid
      gap="5"
      pt="40"
      templateColumns="1fr"
      alignItems="center"
      minH="container.sm"
    >
      <Flex
        direction="column"
        align={{ base: "center", lg: "flex-start" }}
        justifyContent="center"
        justifySelf={{ base: "center", lg: "flex-start" }}
        textAlign={{ base: "center", lg: "left" }}
        gap="6"
        pb="6"
        zIndex="2"
      >
        <Heading color="whiteAlpha.900" size="2xl" maxW="18ch">
          All of who you are, condensed into a single link.
        </Heading>
        <Text color="whiteAlpha.900" fontSize="md" maxW="40ch">
          Connect with others and promote your creations, content, & products
          with a single bio link.
        </Text>
        <Flex direction={{ base: "column", lg: "row" }} justifyContent="space-between" gap="5">
          <InputGroup size="md" maxW={{ lg: "64" }}>
            <InputLeftAddon children="link.hub/" />
            <Input
              placeholder="yourname"
              backgroundColor="whiteAlpha.900"
              value={name}
              onChange={(e) => setName(e.target.value)}
            />
          </InputGroup>
          <Button>Claim your linkhub</Button>
        </Flex>
      </Flex>
      <Image
        position={{ lg: "absolute" }}
        right={{ lg: "5", xl: "48" }}
        justifySelf={{ base: "center", lg: "flex-end" }}
        src="/images/hero.svg"
        alt="Product illustration"
        minW={{ lg: "950px" }}
        mr={{ base: "0", lg: "-96" }}
      />
    </Grid>
  );
}
