import React from "react";
import Head from "next/head";
import NextLink from "next/link";
import {
  Box,
  Flex,
  Heading,
  HStack,
  VStack,
  Link,
  Show,
  Hide,
  IconButton,
  useDisclosure,
  Drawer,
  DrawerOverlay,
  DrawerContent,
  DrawerCloseButton,
  DrawerBody,
  LinkBox,
  LinkOverlay,
  Divider,
  Text,
} from "@chakra-ui/react";
import Button from "@/components/button";
import { HiOutlineMenu } from "react-icons/hi";

function Navbar() {
  const { isOpen, onOpen, onClose } = useDisclosure();
  const navLinks = [
    { text: "Features", href: "#features" },
    { text: "Got Questions?", href: "#questions" },
  ];
  return (
    <>
      <Flex
        w="full"
        justifyContent="space-between"
        backgroundColor="whiteAlpha.900"
        rounded="2xl"
        px={{ base: "5", lg: "20" }}
        py="3"
        wrap="wrap"
      >
        <HStack spacing="8" align="center">
          <Heading size={{ base: "md", lg: "lg" }}>Linkhub</Heading>
          <Show above="md">
            {navLinks.map((link, idx) => (
              <Link
                key={idx}
                as={NextLink}
                href={link.href}
                fontSize={{ base: "sm", lg: "md" }}
                color="gray.600"
              >
                {link.text}
              </Link>
            ))}
          </Show>
        </HStack>
        <HStack>
          <Button variant="outline" size={{ base: "sm", lg: "md" }}>
            Log In
          </Button>
          <Button variant="solid" size={{ base: "sm", lg: "md" }}>
            Sign Up
          </Button>
          <Hide above="md">
            <IconButton
              aria-label="Nav Links"
              icon={<HiOutlineMenu />}
              onClick={onOpen}
            />
          </Hide>
        </HStack>
      </Flex>
      <Drawer placement="right" isOpen={isOpen} onClose={onClose} size="full">
        <DrawerOverlay />
        <DrawerContent>
          <DrawerCloseButton />
          <DrawerBody>
            <VStack spacing="5" pt="14">
              {navLinks.map((link, idx) => (
                <React.Fragment key={idx}>
                  <LinkBox as="div" w="full" p="3" rounded="md" _hover={{ backgroundColor: "gray.100" }}>
                    <LinkOverlay as={NextLink} href={link.href}>
                      <Text as="b">
                        {link.text}
                      </Text>
                    </LinkOverlay>
                  </LinkBox>
                  {(idx !== navLinks.length - 1) && <Divider />}
                </React.Fragment>
              ))}
            </VStack>
          </DrawerBody>
        </DrawerContent>
      </Drawer>
    </>
  );
}

export default function LandingPage() {
  return (
    <>
      <Head>
        <title>Linkhub: link in bio tool</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Box
        backgroundColor="gray.800"
        minW="100vw"
        minH="100vh"
        pt="20px"
        overflowX="clip"
      >
        <Box w={["90%", "80%"]} mx="auto">
          <Navbar />
        </Box>
      </Box>
    </>
  );
}
