import Head from "next/head";
import NextLink from "next/link";
import { Box, Flex, Heading, Link, Text, useToast } from "@chakra-ui/react";
import { LoginProps, LoginSchema } from "@/modules/auth";
import { useForm } from "react-hook-form";
import { zodResolver } from "@hookform/resolvers/zod";
import Button from "@/components/ui/button";
import Input from "@/components/ui/forms/input";
import { useRouter } from "next/router";
import { signIn } from "next-auth/react";
import { useState } from "react";

export default function Login() {
  const router = useRouter();
  const [isLoading, setIsLoading] = useState(false);
  const toast = useToast();

  const {
    register,
    handleSubmit,
    formState: { errors },
  } = useForm<LoginProps>({
    resolver: zodResolver(LoginSchema),
  });

  const onSubmit = handleSubmit(async (values) => {
    setIsLoading(true);
    const res = await signIn("credentials", {
      username: values.username,
      password: values.password,
      redirect: false,
    });

    if (res?.ok) {
      router.push("/admin");
    } else {
      setIsLoading(false);
      toast({
        title: res?.error,
        status: "error",
        isClosable: true,
      });
    }
  });

  return (
    <>
      <Head>
        <title>Login - Linkhub</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Box
        backgroundColor="gray.50"
        minW="100vw"
        minH="100vh"
        py="16"
        overflowX="clip"
      >
        <Flex
          w={["90%", "80%"]}
          mx="auto"
          mt={{ base: "6", lg: "20" }}
          direction="column"
          alignItems="center"
        >
          <Heading size="2xl" textAlign="center">
            Welcome Back
          </Heading>
          <Text textAlign="center" color="gray.500" fontSize="sm" my="4">
            Login to your Linkhub.
          </Text>
          <form
            onSubmit={onSubmit}
            style={{
              display: "flex",
              flexDirection: "column",
              gap: "0.5rem",
              minWidth: "35ch",
            }}
          >
            <Input
              label="Username"
              name="username"
              placeholder="yourname"
              register={register}
              error={errors.username}
              size="sm"
              variant="outline"
              leftAddon="link.hub/"
              required
            />
            <Input
              label="Password"
              name="password"
              type="password"
              placeholder="6+ characters"
              register={register}
              error={errors.password}
              size="sm"
              required
            />
            <Button type="submit" mt="4" isLoading={isLoading}>
              Submit
            </Button>
          </form>
          <Text fontSize="sm" pt="6" color="gray.500">
            Don't have an account?{" "}
            <Link as={NextLink} href="/sign-up" color="cyan.600">
              Create one
            </Link>
          </Text>
          <Link
            as={NextLink}
            href="/"
            fontWeight="bold"
            color="gray.500"
            pt="4"
          >
            Linkhub
          </Link>
        </Flex>
      </Box>
    </>
  );
}
