import Head from "next/head";
import { Box, Divider, Flex, Heading, Text, useToast } from "@chakra-ui/react";
import { SignUpProps, SignUpSchema } from "@/modules/auth";
import { useForm } from "react-hook-form";
import { zodResolver } from "@hookform/resolvers/zod";
import { useMutation } from "react-query";
import Button from "@/components/ui/button";
import Input from "@/components/ui/forms/input";
import { useRouter } from "next/router";
import { signUp } from "@/modules/auth/api";
import { useState } from "react";

export default function SignUp() {
  const router = useRouter();
  const toast = useToast();
  const [isLoading, setIsLoading] = useState(false);
  const signUpMutation = useMutation(signUp, {
    onSuccess: () => {
      router.push("/login");
    },
    onError: (error) => {
      setIsLoading(false);
      toast({
        title: (error as any).response.data.message,
        status: "error",
        isClosable: true,
      });
    }
  });

  const {
    register,
    handleSubmit,
    formState: { errors },
  } = useForm<SignUpProps>({
    resolver: zodResolver(SignUpSchema),
    defaultValues: {
      username: router.query.username as string,
    },
  });

  const onSubmit = handleSubmit((values) => {
    setIsLoading(true);
    signUpMutation.mutate(values)
  });

  return (
    <>
      <Head>
        <title>Sign Up - Linkhub</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Box
        backgroundColor="gray.50"
        minW="100vw"
        minH="100vh"
        py="8"
        overflowX="clip"
      >
        <Flex
          w={["90%", "80%"]}
          mx="auto"
          mt={{ base: "6", lg: "20" }}
          direction="column"
          alignItems="center"
        >
          <Heading size="2xl" textAlign="center">
            Create your account
          </Heading>
          <Text textAlign="center" color="gray.500" fontSize="sm" my="4">
            Choose your Linkhub username. You can always change it later.
          </Text>
          <form
            onSubmit={onSubmit}
            style={{
              display: "flex",
              flexDirection: "column",
              gap: "0.5rem",
              minWidth: "35ch",
            }}
          >
            <Input
              label="Username"
              name="username"
              placeholder="yourname"
              register={register}
              error={errors.username}
              size="sm"
              variant="outline"
              leftAddon="link.hub/"
              required
            />
            <Input
              label="Email"
              name="email"
              placeholder="ex: james@mail.com"
              register={register}
              error={errors.email}
              size="sm"
              required
            />
            <Input
              label="Password"
              name="password"
              type="password"
              placeholder="6+ characters"
              register={register}
              error={errors.password}
              size="sm"
              required
            />
            <Input
              label="Confirm Password"
              name="confirmPassword"
              type="password"
              placeholder="6+ characters"
              register={register}
              error={errors.confirmPassword}
              size="sm"
              required
            />
            <Button type="submit" mt="4" isLoading={isLoading}>
              Submit
            </Button>
            <Flex align="center" my="1">
              <Divider borderColor="gray.300" />
              <Text padding="2" color="gray.300">or</Text>
              <Divider borderColor="gray.300" />
            </Flex>
          </form>
        </Flex>
      </Box>
    </>
  );
}
