import Head from "next/head";
import { useSession } from "next-auth/react";
import {
  Box,
  Flex,
  Spinner,
} from "@chakra-ui/react";
import AnalyticsBar from "@/components/admin-links/analytics-bar";
import LinksForm from "@/components/admin-links/links-form";
import { Session } from "next-auth";
import AdminNavbar from "@/components/admin-links/navbar";

export default function Admin() {
  const { data: session, status } = useSession();

  return (
    <>
      <Head>
        <title>Linkhub Admin</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Box
        backgroundColor="gray.100"
        minW="100vw"
        minH="100vh"
        py="8"
        overflowX="clip"
      >
        <Flex w="95%" mx="auto" direction="column" alignItems="center">
          <AdminNavbar />
          {status === "loading" ? (
            <Spinner size="lg" mt="16"/>
          ) : (
            <Box my="4" minW="full">
              <AnalyticsBar />
              <LinksForm session={session as Session} />
            </Box>
          )}
        </Flex>
      </Box>
    </>
  );
}
